#!/command/with-contenv bash

s6-echo "Core quit, stopping Web"
service 20-web stop

s6-echo "Done, stopping Container"
foreground { redirfd -w 1 /run/s6-linux-init-container-results/exitcode echo 0 }
/run/s6/basedir/bin/halt