services:
  twwbot:
    container_name: twitchalerts
    hostname: twitchalerts
    build:
      context: /opt/twitchalerts
      dockerfile: /opt/twitchalerts/twitchalerts.Dockerfile
    ports:
      - "3000:3000/tcp"
    environment:
      DATABASE: "Your Database URL"
      DISCORD_CLIENT_ID: "YOUR_DISCORD_CLIENT_ID"
      DISCORD_CLIENT_SECRET: "YOUR_DISCORD_CLIENT_SECRET"
      DISCORD_REDIRECT_URI: "https://thewishingwell.uk.to/connect"
      PORT: 3000
      TWITCH_BOT_CLIENT_ID: "YOUR_TWITCH_CLIENT_ID"
      TWITCH_BOT_CLIENT_SECRET: "YOUR_TWITCH_CLIENT_SECRET"
      TWITCHBOT: "Bot secret of your Discord application"